#!/usr/bin/env python3

import os
import subprocess
import sys

# Bootstrapping
# =============

# Make sure the KNinja repo is available.
#
subprocess.check_call(['git', 'submodule', 'update', '--init', '--recursive'])
extdir = 'ext'
sys.path.append(os.path.join(os.path.dirname(__file__), extdir))

from kninja import *

# Build
# =====

proj = KProject(extdir = extdir)
def build_dafny(backend, alias, flags = ''):
    return proj.definition( alias         = alias
                          , backend       = backend
                          , main          = 'dafny.md'
                          , directory     = proj.builddir('defn', backend)
                          , flags         = '--syntax-module DAFNY ' + flags
                          )

ocaml_exec = build_dafny(backend = 'ocaml', alias = 'dafny-ocaml-exec')
java_exec  = build_dafny(backend = 'java', alias = 'dafny-java-exec', flags = '-O3 --non-strict')

ocaml_exec.tests(glob = 't/*.dfy', expected = 't/expected')
java_exec.tests(glob = 't/*.dfy', expected = 't/expected')
java_exec.proofs(glob = 'unit-tests.k', alias = 'unit-tests')

proj.main()
