#!/usr/bin/env python3

import os
import subprocess
import sys

# Bootstrapping
# =============

# Make sure the KNinja repo is available.
#
subprocess.check_call(['git', 'submodule', 'update', '--init', '--recursive'])
extdir = 'ext'
sys.path.append(os.path.join(os.path.dirname(__file__), extdir))

from kninja import *

# Build
# =====

proj = KProject(extdir = extdir)
def build_dafny(backend, alias, flags = ''):
    return proj.definition( alias         = alias
                          , backend       = backend
                          , main          = 'dafny.md'
                          , directory     = proj.builddir('defn', backend)
                          , kompile_flags = '--syntax-module DAFNY ' + flags
                          , krun_flags    = '--search-final'
                          )

haskell  = build_dafny(backend = 'haskell', alias = 'h-dafny')
haskell.tests(glob = 't/*.dfy', alias='test-haskell')
haskell.proofs(glob = 'unit-tests.k', alias = 'h-unit-tests')

java = build_dafny(backend = 'java', alias = 'j-dafny')
java.tests(glob = 't/*.dfy')
java.proofs(glob = 'unit-tests.k', alias = 'j-unit-tests')

proj.main()
